# Generated by Django 3.0.5 on 2020-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200604_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itm_LeverTijd',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Levertijd (dagen)'),
        ),
        migrations.AddField(
            model_name='item',
            name='itm_VoorraadStatus',
            field=models.CharField(choices=[('V', 'op voorraad'), ('I', 'in bestelling'), ('T', 'tijdelijk niet leverbaar')], default='V', max_length=1, verbose_name='Voorraad status'),
        ),
    ]
